### ISSUE TITLE
Keep getting ERROR: URLShortener when trying to use this

### ISSUE THREAD

**Issue by ghost** [Fuhrmann/keypirinha-url-shortener#2]
I have a similar issue to other one posted here. 

I opened and modified the config url.ini file as stated in the README. I even copied the default url.ini info over to the user url.ini file. Still no joy. 

I've tried the 3 Supported services that don't require the user to get an API key:
Google (default)
TinyURL
isgood

From Keypirinha's console:

18:19:35.722 ** ERROR: URLShortener.URLShortener: b'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "forbidden",\n    "message": "Forbidden"\n   }\n  ],\n  "code": 403,\n  "message": "Forbidden"\n }\n}\n'
18:19:35.723 Python: Traceback (most recent call last):
18:19:35.723 Python:   File "C:\Users\%UserName%\AppData\Roaming\Keypirinha\InstalledPackages\URLShortener.keypirinha-package\urlshortener.py", line 108, in on_suggest
18:19:35.723 Python:   File "C:\Users\%UserName%\AppData\Roaming\Keypirinha\InstalledPackages\URLShortener.keypirinha-package\services\google.py", line 10, in shorten
18:19:35.723 Python:   File "C:\Users\%UserName%\AppData\Roaming\Keypirinha\InstalledPackages\URLShortener.keypirinha-package\services\service.py", line 22, in post_request
18:19:35.723 Python:   File "lib\urllib\request.py", line 223, in urlopen
18:19:35.723 Python:   File "lib\urllib\request.py", line 532, in open
18:19:35.723 Python:   File "lib\urllib\request.py", line 642, in http_response
18:19:35.723 Python:   File "lib\urllib\request.py", line 570, in error
18:19:35.723 Python:   File "lib\urllib\request.py", line 504, in _call_chain
18:19:35.723 Python:   File "lib\urllib\request.py", line 650, in http_error_default
18:19:35.723 Python: urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by Fuhrmann** [comment]
This is really strange error. One thing I know is that google URL shortener doesn't exists anymore, maybe this is the culprit. I'm don't have a Windows installation available at the moment to test it.

**Comment by ghost** [comment]
@Fuhrmann Thanks for your response. Yeah, that makes sense as to why Google doesn't work but at least TinyURL should. 

OK, so I went back to the config file (oddly, the user config file was now blank, so I had to re-copy/paste the info from the main one) and commented out everything Google, changing main_service=tinyurl. It now works. Although, commenting out Google may not have been the 'solution' since I did have to reboot my computer due to Windows updates. However, I tried isgood just to check, didn't work with the same error. At least TinyURL does. =)

**Comment by mbaas2** [comment]
Happened to me, too. Tinyurl did it :)

**Comment by fridde** [comment]
I'd propose to remove google from the options.

**Comment by Fuhrmann** [comment]
Yes, I'll remove it.

**Comment by Fuhrmann** [comment]
Sorry for the long wait, but I just publish na update. https://github.com/Fuhrmann/keypirinha-url-shortener/commit/6f2ae839f5fbd17f0667e8727f9aa5c8f7571de5 closes this.
